# Generated by Django 4.0.1 on 2022-01-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupuser', '0002_alter_signupuser_country_alter_signupuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
