# Generated by Django 4.0.1 on 2022-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_title', models.CharField(max_length=50)),
                ('language_desc', models.TextField()),
                ('language_tutorial_link', models.CharField(max_length=200)),
                ('language_video_link', models.CharField(max_length=200)),
            ],
        ),
    ]
