# Generated by Django 4.0.1 on 2022-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_link',
            field=models.CharField(max_length=200),
        ),
    ]
